version: "3"

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - /private/tmp/docker/mongodb_fastapi_test:/data/db
    networks:
      - backend

  database_service:
    build:
      context: ./database_service
    command: python3 ./main.py
    volumes:
      - ./database_service:/database_service
    ports:
      - 8000:8000
    env_file:
      - .env
    logging:
      driver: json-file
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:
    driver: bridge
