version: '3.7'

services:
  fastapi:
    container_name: ${COMPOSE_PROJECT_NAME}_fastapi
    build:
      context: ./
    command: python3 ./main.py
    restart: unless-stopped
    volumes:
      - ./database_service:/database_service
    ports:
      - 8000:8000
    env_file:
      - .env
    logging:
      driver: json-file
    depends_on:
      - mongodb

  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
