version: "3"

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - /data:/data/db
    networks:
      - backend

  database_service:
    build:
      context: ./database_service
    command: python3 ./main.py
    volumes:
      - ./database_service/data:/database_service/data
      - ./database_service/logs:/database_service/logs
    ports:
      - 8000:8000
    env_file:
      - database_service/core/back.env
    logging:
      driver: json-file
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:
    driver: bridge
